import { useState } from "react";
import { CircleDollarSign, Plus, ReceiptText, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export default function FinancePanel({ projectId }: { projectId?: number }) {
  const summary = trpc.workspace.financeSummary.useQuery();
  const [description, setDescription] = useState(""); const [amount, setAmount] = useState(""); const [participant, setParticipant] = useState(""); const [percentage, setPercentage] = useState("");
  const ledger = trpc.workspace.createLedgerEntry.useMutation({ onSuccess: () => { summary.refetch(); setDescription(""); setAmount(""); toast.success("Lançamento financeiro registrado."); }, onError: (error) => toast.error(error.message) });
  const royalty = trpc.workspace.createRoyaltySplit.useMutation({ onSuccess: () => { summary.refetch(); setParticipant(""); setPercentage(""); toast.success("Split de royalties registrado."); }, onError: (error) => toast.error(error.message) });
  return <section className="finance-panel panel"><div className="panel-heading"><div><p className="eyebrow">FINANCEIRO / ROYALTIES</p><h2>Faça o dinheiro do estúdio ficar visível</h2></div><CircleDollarSign className="accent-icon" size={20} /></div><div className="finance-metrics"><div><span>A receber</span><strong>R$ {((summary.data?.pendingCents ?? 0) / 100).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</strong></div><div><span>Recebido</span><strong>R$ {((summary.data?.paidCents ?? 0) / 100).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</strong></div><div><span>Splits registrados</span><strong>{summary.data?.royalties.length ?? 0}</strong></div></div><div className="finance-grid"><div className="finance-form"><div className="finance-form-title"><ReceiptText size={15} /> Novo lançamento</div><Input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Descrição do recebimento" /><Input value={amount} onChange={(e) => setAmount(e.target.value)} inputMode="decimal" placeholder="Valor em R$" /><Button className="primary-button" disabled={!description || !amount || ledger.isPending} onClick={() => ledger.mutate({ description, amountCents: Math.round(Number(amount.replace(",", ".")) * 100), status: "pending" })}><Plus size={14} /> Registrar</Button></div><div className="finance-form"><div className="finance-form-title"><UsersRound size={15} /> Novo split</div><Input value={participant} onChange={(e) => setParticipant(e.target.value)} placeholder="Nome do participante" /><Input value={percentage} onChange={(e) => setPercentage(e.target.value)} inputMode="decimal" placeholder="Percentual, ex.: 50" /><Button className="ghost-button" disabled={!projectId || !participant || !percentage || royalty.isPending} onClick={() => projectId && royalty.mutate({ projectId, participantName: participant, role: "composição / produção", percentage })}><Plus size={14} /> Salvar split</Button></div></div></section>;
}
